### ISSUE TITLE
Mudança na regra da operação de débito

### ISSUE THREAD

**Issue by LucasPoke** [larissaleite/HamptonsBank#1]
O saldo mínimo em conta deverá ser R$2,00. Esta restrição deve ser informada ao usuário através de mensagem caso o valor a ser debitado ultrapasse o saldo mínimo em conta.

**Comment by LucasPoke** [comment]
### Análise da viabilidade da mudança
- Impacto: baixo
- Custo: $$
- Cronograma: nenhuma alteração no cronograma
- Prazo estimado: 12/04/2016

Viabilidade: **viável**

**Comment by larissaleite** [comment]
### Validação da implementação da mudança

Tag de testes associada: t01.03
Interessados na validação: @LucasPoke, @LarissaLeite

Nenhum problema encontrado

Responsavel pela validação: @LucasPoke

**Comment by larissaleite** [comment]
Integrada na versão 01.03
