### ISSUE TITLE
X001 - Alteração na operação de crédito 

### ISSUE THREAD

**Issue by LucasPoke** [larissaleite/HamptonsBank#2]
Alteração na operação de crédito para que seja informada uma descrição para a operação.

**Obs: Não deve ser feita em paralelo com a issue** #3

**Comment by LucasPoke** [comment]
### Análise da viabilidade da mudança
- Impacto: baixo
- Custo: $$
- Cronograma: nenhuma alteração no cronograma
- Prazo estimado: 12/04/2016

Viabilidade: **viável**

**Comment by larissaleite** [comment]
### Validação da implementação da mudança

Tag de testes associada: t01.03.01
Interessados na validação: @LucasPoke, @LarissaLeite

Nenhum problema encontrado

Responsavel pela validação: @LucasPoke

**Comment by larissaleite** [comment]
Integrada na versão 01.03.01
