### ISSUE TITLE
Bug na funcionalidade bônus

### ISSUE THREAD

**Issue by LucasPoke** [larissaleite/HamptonsBank#4]
O bônus deve ser de 3% do valor de cada operação.

**Comment by LucasPoke** [comment]
### Análise da viabilidade da mudança
- Impacto: baixo
- Custo: $$
- Cronograma: nenhuma alteração no cronograma
- Prazo estimado: 12/04/2016

Viabilidade: **viável**

**Comment by larissaleite** [comment]
### Validação da implementação da mudança

Tag de testes associada: t01.03.03
Interessados na validação: @LucasPoke, @LarissaLeite

Nenhum problema encontrado

Responsavel pela validação: @LucasPoke

**Comment by larissaleite** [comment]
Integrada na versão 01.03.03
